#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES：ybrain vault 备份链路（Gitee 部署密钥 + Mac 端 Obsidian Git）
#
# 运行位置：你的 Mac；服务器步骤经 ssh 别名 ybrain 执行（deploy/README 第一节）。
# 依据：票据 25、.scratch/exobrain/prototypes/backup-plan.md、deploy/README 第四节。
# 可以随时 Ctrl-C 停下重跑：密钥生成与 .env 写入都是幂等的。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# 本向导唯一落值的地方是**服务器**的 /opt/ybrain/.env（库里没有本地 .env 要写），
# 把 ENV_FILE 指过去，收尾汇总才会说清写在哪儿。
ENV_FILE="/opt/ybrain/.env"

# 服务器侧 .env 的幂等 upsert：与库里的 write_env 同语义，只是经 ssh 落到服务器并保住 600 权限。
_write_server_env() {
  local key="$1" value="$2"
  if ssh -o ConnectTimeout=15 ybrain "sudo sh -c 'grep -vE \"^${key}=\" /opt/ybrain/.env > /tmp/.env.next || true; printf \"%s=%s\\n\" \"${key}\" \"${value}\" >> /tmp/.env.next; mv /tmp/.env.next /opt/ybrain/.env; chmod 600 /opt/ybrain/.env'"; then
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → 服务器 /opt/ybrain/.env\n' "$GREEN" "$RESET" "$key"
    return 0
  fi
  SKIPPED+=("服务器 .env 里的 $key（手动加一行到 /opt/ybrain/.env）")
  warn "写服务器 .env 失败：$key"
  return 1
}

# 复制到剪贴板，跨平台；都没有就提示手工复制。
_clip() {
  if   command -v pbcopy  >/dev/null 2>&1; then pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then wl-copy
  elif command -v xclip   >/dev/null 2>&1; then xclip -selection clipboard
  else warn "没有可用的剪贴板工具，请手动复制上面的内容"; cat >/dev/null; fi
}

banner "ybrain vault 备份链路（Gitee + Obsidian）"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "自检：ssh 与服务器现状"
say "本向导在你的 Mac 上跑，服务器步骤通过 ssh 别名 ybrain 执行。"
if ! ssh -o ConnectTimeout=10 ybrain true >/dev/null 2>&1; then
  warn "ssh ybrain 不通：先确认 ~/.ssh/config 的别名与密钥（deploy/README 第一节），再重跑本向导。"
  exit 1
fi
say "✓ ssh ybrain 可用"
note "服务器上的 sudo 需要免密（或认证已缓存），否则后面的 sudo 命令会卡住。"
step "容器状态（应看到 ybrain-ybrain-1 在跑）"
ssh ybrain 'sudo docker ps --format "    {{.Names}}  {{.Status}}"' || true
KEYSTATE=$(ssh ybrain 'if [ -s /opt/ybrain/gitee_deploy_key ]; then echo "已有非空密钥"; else echo "空占位文件"; fi' || echo "读不到")
say "部署密钥文件：${KEYSTATE}（阶段 3 处理）"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Gitee：注册账号并新建私有仓库"
step "没有 Gitee 账号先注册；已有账号直接登录"
open_url "https://gitee.com/signup"
pause "注册/登录完成后按回车"
step "新建仓库：名称填 ybrain-vault，选「私有」，并且不要勾「初始化仓库」（README / .gitignore / 许可证都不要）"
note "服务器上的 vault 已有 10 个提交，远端仓库要是空的，否则两边历史没法合并。"
open_url "https://gitee.com/projects/new"
ask GITEE_ACCOUNT "粘贴你的 Gitee 空间地址（个人主页 gitee.com/<这一段>）:"
note "远程地址将是 git@gitee.com:${GITEE_ACCOUNT}/ybrain-vault.git"
pause "仓库建好了？"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "服务器：生成部署密钥（只授权这一个仓库）"
if ssh ybrain 'sudo test -s /opt/ybrain/gitee_deploy_key'; then
  say "已有非空密钥，跳过生成（重跑不会覆盖它）"
else
  step "先删掉票据 17 留下的 0 字节占位文件，再生成 ed25519 密钥（不设口令）"
  ssh ybrain "sudo rm -f /opt/ybrain/gitee_deploy_key /opt/ybrain/gitee_deploy_key.pub && sudo ssh-keygen -t ed25519 -f /opt/ybrain/gitee_deploy_key -N '' -C 'ybrain-deploy' >/dev/null && sudo chmod 600 /opt/ybrain/gitee_deploy_key" \
    && say "✓ 已生成 /opt/ybrain/gitee_deploy_key" \
    || warn "生成失败：手工执行 deploy/README 第四节里的 ssh-keygen 命令"
fi
PUB=$(ssh ybrain 'sudo cat /opt/ybrain/gitee_deploy_key.pub' | tail -1)
printf '%s' "$PUB" | _clip
say "✓ 公钥已复制到剪贴板，内容开头是：${PUB:0:60}…"
note "公钥不是秘密；私钥留在服务器 /opt/ybrain/gitee_deploy_key（600），永不复制出来。"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Gitee：把公钥登记为仓库部署公钥"
step "打开仓库主页 → 右上/顶部「管理」→ 左侧「部署公钥管理」→「添加部署公钥」"
open_url "https://gitee.com/${GITEE_ACCOUNT}/ybrain-vault"
step "标题填 ybrain-server；「公钥」粘贴剪贴板里那一行"
step "表单里若有「启用推送权限 / 允许写入」开关，勾上——服务器要往这个仓库推提交"
warn "Gitee 官方文档把部署公钥写成只拉取；没有该开关也能继续，阶段 6 会实测推送并在失败时给替代方案。"
pause "添加完成？"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "服务器：写入远程地址并重建容器"
_write_server_env YBRAIN_VAULT_REMOTE "git@gitee.com:${GITEE_ACCOUNT}/ybrain-vault.git" || true
step "重建容器（compose 只在重建时读 .env）"
ssh ybrain 'cd /opt/ybrain && sudo docker compose up -d --force-recreate ybrain' >/dev/null 2>&1 \
  && say "✓ 容器已重建" \
  || warn "重建失败，手工跑：ssh ybrain 'cd /opt/ybrain && sudo docker compose up -d --force-recreate ybrain'"
note "票据 29：容器重建后插件要等一次 Web/接口请求才加载，下一阶段顺带预热。"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "验证：服务器能推到 Gitee"
step "先预热插件：打开 Web 界面并登录一次（同时复验 Mac 经 tailnet 可访问）"
open_url "http://100.64.0.1:4096/"
pause "登录过 Web 界面后按回车"
sleep 5
say "插件日志里的远程配置（应出现「远程 origin → git@gitee.com…」）"
ssh ybrain 'sudo docker logs ybrain-ybrain-1 2>&1 | grep -i "vault git" | tail -1' || true
step "提交遗留改动并做首次推送（下方会打印 git 的输出）"
ssh ybrain 'sudo docker exec ybrain-ybrain-1 sh -c "git -C /opt/ybrain/vault add -A && git -C /opt/ybrain/vault -c user.name=ybrain -c user.email=ybrain@localhost commit -q -m \"chore: 备份链路验证\" || true; git -C /opt/ybrain/vault push -u origin main"' \
  || warn "push 返回非零，看上面 git 的报错"
LOCAL_SHA=$(ssh ybrain 'sudo docker exec ybrain-ybrain-1 git -C /opt/ybrain/vault rev-parse HEAD' 2>/dev/null | tail -1 || true)
REMOTE_SHA=$(ssh ybrain 'sudo docker exec ybrain-ybrain-1 git -C /opt/ybrain/vault rev-parse origin/main' 2>/dev/null | tail -1 || true)
if [ -n "$REMOTE_SHA" ] && [ "$LOCAL_SHA" = "$REMOTE_SHA" ]; then
  say "✓ 推送成功：本地与 origin/main 都是 ${LOCAL_SHA:0:9}"
else
  warn "推送未成功（本地 ${LOCAL_SHA:0:9}，远端 ${REMOTE_SHA:-无}）"
  step "替代方案：给这个仓库的部署公钥没有写权限时，把同一把公钥也加到账户公钥 https://gitee.com/profile/sshkeys"
  note "代价是权限范围变成你名下所有仓库（离开最小权限设计），请在票据 25 记一笔取舍。"
  SKIPPED+=("Gitee 推送：部署公钥权限不足，需按上面的替代方案处理")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Mac：账户公钥与 clone（Mac 要能推自己的手写改动）"
note "部署公钥只覆盖服务器与那一个仓库；Mac 端的手写改动要推回去，用的是账户级公钥。"
if [ -f "$HOME/.ssh/id_ed25519.pub" ]; then
  say "已有 $HOME/.ssh/id_ed25519.pub，直接用它"
else
  step "生成 Mac 账户公钥（一路回车，不设口令）"
  ssh-keygen -t ed25519 -C "ybrain-mac" -f "$HOME/.ssh/id_ed25519" -N '' >/dev/null \
    && say "✓ 已生成 $HOME/.ssh/id_ed25519" \
    || warn "生成失败：手工跑 ssh-keygen -t ed25519 -C 'ybrain-mac'"
fi
printf '%s' "$(cat "$HOME/.ssh/id_ed25519.pub")" | _clip
say "✓ Mac 公钥已复制到剪贴板"
open_url "https://gitee.com/profile/sshkeys"
step "「添加公钥」→ 粘贴 → 按提示验证账号密码"
pause "添加完成？"
step "验证连接（应返回 Hi <你的用户名>! You've successfully authenticated…）"
ssh -o StrictHostKeyChecking=accept-new -T git@gitee.com 2>&1 | tail -2 || true
ask VAULT_LOCAL_PATH "本地 vault 目录（回车用 ~/Documents/ybrain-vault）:"
[ -n "$VAULT_LOCAL_PATH" ] || VAULT_LOCAL_PATH="$HOME/Documents/ybrain-vault"
if [ -d "$VAULT_LOCAL_PATH/.git" ]; then
  say "✓ $VAULT_LOCAL_PATH 已是 Git 仓库，跳过 clone"
else
  step "clone Gitee 上的 vault 到 $VAULT_LOCAL_PATH"
  git clone "git@gitee.com:${GITEE_ACCOUNT}/ybrain-vault.git" "$VAULT_LOCAL_PATH" \
    && say "✓ clone 完成" \
    || warn "clone 失败：确认账户公钥已加、仓库地址正确"
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Obsidian：打开 vault 并配置 Obsidian Git"
step "Obsidian →「打开文件夹作为仓库」→ 选 $VAULT_LOCAL_PATH"
step "设置 → 第三方插件 → 关闭「安全模式」→ 浏览 → 搜 Obsidian Git → 安装 → 启用"
say "然后把插件设置调成这样（对应 deploy/README 第四节）："
step "Pull updates on startup：开"
step "Auto pull interval (minutes)：10"
step "Auto backup interval (minutes)：10"
step "Disable push：关"
pause "配好了？"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "收尾核对"
step "刷新 Gitee 仓库首页，应能看到刚推上去的提交"
open_url "https://gitee.com/${GITEE_ACCOUNT}/ybrain-vault"
step "Obsidian 里应能看到笔记与 0-Inbox / 3-Resources 等目录，PARA 结构正确"
say "之后：每次提炼闭环都会自动 commit + push；周复盘会报告最近推送时间与 dead 任务数。"
step "按票据 13 约定，把本次配置记进密码管理器（Gitee 账号、远程地址、两把密钥的位置）"
note "远程地址：git@gitee.com:${GITEE_ACCOUNT}/ybrain-vault.git（写在服务器 /opt/ybrain/.env，不入 Git）"
pause
# ──────────────────────────────────────────────────────────────────────────

finish